In [2]:
import pandas as pd
import numpy as np

np.random.seed(33)

df = pd.read_csv("../data/allOnlyTriage.csv")
df = df.drop("Unnamed: 0", axis=1)

df.head()

dep_name.C  dep_name.B  dep_name.A  esi.1  esi.2  esi.3  esi.4  esi.5  \
0           0           1           0    0.0    0.0    0.0    1.0    0.0   
1           0           1           0    0.0    0.0    0.0    1.0    0.0   
2           0           1           0    0.0    1.0    0.0    0.0    0.0   
3           0           0           1    0.0    1.0    0.0    0.0    0.0   
4           0           0           1    0.0    0.0    1.0    0.0    0.0   

    age  gender.Female  ...  cc_vaginalpain  cc_weakness  cc_wheezing  \
0  40.0              0  ...             0.0          0.0          0.0   
1  66.0              0  ...             0.0          0.0          0.0   
2  66.0              0  ...             0.0          0.0          0.0   
3  66.0              0  ...             0.0          0.0          0.0   
4  84.0              1  ...             0.0          0.0          0.0   

   X.cc_withdrawal.alcohol.  cc_woundcheck  cc_woundinfection  \
0                       0.0            0.0                0.0   
1                       0.0            0.0                0.0   
2                       0.0            0.0                0.0   
3                       0.0            0.0                0.0   
4                       0.0            0.0                0.0   

   X.cc_woundre.evaluation.  cc_wristinjury  cc_wristpain  Y  
0                       0.0             0.0           0.0  0  
1                       0.0             0.0           0.0  0  
2                       0.0             0.0           0.0  0  
3                       0.0             0.0           0.0  0  
4                       0.0             0.0           0.0  1  

[5 rows x 303 columns]

In [3]:
for col in df.columns:
    ratio = round(100* df[col].isnull().sum() / len(df), 2)
    print(col, str(ratio) + '%')

dep_name.C 0.0%
dep_name.B 0.0%
dep_name.A 0.0%
esi.1 0.44%
esi.2 0.44%
esi.3 0.44%
esi.4 0.44%
esi.5 0.44%
age 0.0%
gender.Female 0.0%
gender.Male 0.0%
ethnicity.Hispanic.or.Latino 0.0%
ethnicity.Non.Hispanic 0.0%
ethnicity.Patient.Refused 0.0%
ethnicity.Unknown 0.0%
race.American.Indian.or.Alaska.Native 0.0%
race.Asian 0.0%
race.Black.or.African.American 0.0%
race.Native.Hawaiian.or.Other.Pacific.Islander 0.0%
race.Other 0.0%
race.Patient.Refused 0.0%
race.Unknown 0.0%
race.White.or.Caucasian 0.0%
lang.English 0.0%
lang.Other 0.0%
religion.Baptist 0.0%
religion.Catholic 0.0%
religion.Christian 0.0%
religion.Episcopal 0.0%
religion.Jehovah.s.Witness 0.0%
religion.Jewish 0.0%
religion.Methodist 0.0%
religion.Muslim 0.0%
religion.None 0.0%
religion.Other 0.0%
religion.Pentecostal 0.0%
religion.Protestant 0.0%
religion.Unknown 0.0%
maritalstatus.Civil.Union 0.0%
maritalstatus.Divorced 0.0%
maritalstatus.Legally.Separated 0.0%
maritalstatus.Life.Partner 0.0%
maritalstatus.Married 0.0%
mar

## Find the NA ratio higher than 5%

In [4]:
count = 0
print("original number of columns",len(df.columns))
for col in df.columns:
    ratio = round(100* df[col].isnull().sum() / len(df), 2)
    if ratio>=5:
        count = count+1
        print(col)
        df = df.drop(col,axis=1)
#     print(col, str(round(100* df[col].isnull().sum() / len(df), 2)) + '%')

print(count)
print("after processing:", len(df.columns))

original number of columns 303
triage_vital_hr
triage_vital_sbp
triage_vital_dbp
triage_vital_rr
triage_vital_o2
triage_vital_o2_device
triage_vital_temp
7
after processing: 296


## Delete the row with NA

In [7]:
cleaned_df = df.dropna()
print(cleaned_df.shape)
print(df.shape)
df = df.dropna()

(534730, 296)


## Save the cleaned dataframe to csv

In [8]:
df.to_csv("../data/cleanedOnlyTriage.csv")

In [9]:
## Split the data into training and testing data
from sklearn.model_selection import train_test_split

training_data, testing_data = train_test_split(df, test_size=0.2, random_state=25)

print(f"No. of training examples: {training_data.shape[0]}")
print(f"No. of testing examples: {testing_data.shape[0]}")

No. of training examples: 427784
No. of testing examples: 106946


In [10]:
y_train = training_data.iloc[:,-1]
y_test = testing_data.iloc[:,-1]
X_train = training_data.iloc[:,:-1]
X_test = testing_data.iloc[:,:-1]

In [11]:
y_train = np.array(y_train)
y_test = np.array(y_test)
X_train = np.array(X_train)
X_test = np.array(X_test)

In [15]:
print(X_train[:100,])
print(y_train[:100,])


[[0. 0. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 1 0
 0 0 1 0 1 0 1 0 1 1 0 0 1 1 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 1 0 1 0 0 1 1
 0 1 0 0 1 1 0 0 0 0 1 0 1 0 1 0 0 0 0 0 1 0 0 1 0 0]


In [16]:
from sklearn.svm import SVC
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
sv_clf = SVC(kernel="linear",random_state=1)
sv_clf.fit(X_train[:100,], y_train[:100,])

SVC(kernel='linear', random_state=1)

In [21]:
from sklearn.metrics import accuracy_score
sv_clf_pred = sv_clf.predict(X_test[:10,])
sv_clf_acc = accuracy_score(y_test[:10,],sv_clf_pred)
sc_clf_acc_format = round(sv_clf_acc*100,2)
print("Accuracy of linear SVM model", sc_clf_acc_format)

Accuracy of linear SVM model 80.0
